apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: example-client
  namespace: example-client
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: example-client
  minReplicas: 1
  maxReplicas: 10
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 0
  metrics:
    - type: External
      external:
        metric:
          name: partition-to-worker-ratio
          selector:
            matchLabels:
              context: f3327714-8d22-44ae-b9c1-840544b398b4
        target:
          type: Value
          value: 1
