apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: example-client
  namespace: example-client
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: example-client
  minReplicas: 1
  maxReplicas: 10
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 0
  metrics:
    - type: External
      external:
        metric:
          name: partition-to-worker-ratio
          selector:
            matchLabels:
              context: 3c0d1a1d-2e58-4032-a7dd-cf93a3eef4d3
        target:
          type: Value
          value: 1
