apiVersion: apps/v1
kind: Deployment
metadata:
  name: ackbar-redis
  namespace: ackbar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ackbar-redis
  template:
    metadata:
      labels:
        app: ackbar-redis
    spec:
      containers:
        - name: redis
          image: redis:latest
          args: ["/usr/local/etc/redis/redis.conf"]
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: storage
              mountPath: /data
            - name: config
              mountPath: /usr/local/etc/redis/redis.conf
              readOnly: true
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: ackbar-redis
        - name: config
          configMap:
            defaultMode: 0666
            name: ackbar-redis
